#!/usr/bin/env bash

echo "synching dotfiles to vcs..."

cp ~/.config/nvim/init.vim ~/dotfiles/vim/nvimrc
cp -r ~/.config/nvim/colors ~/dotfiles/vim/colors
cp ~/.zshrc ~/dotfiles/config/.zshrc
cp ~/tmux.conf ~/dotfiles/config/tmux.conf
cp ~/.config/kitty/kitty.conf ~/dotfiles/config/kitty.conf
cp ~/.config/alacritty/alacritty.yml ~/dotfiles/config/alacritty.yml
cp ~/.gitconfig ~/dotfiles/config/.gitconfig
cp ~/.hyper.js ~/dotfiles/config/.hyper.js

now=`date '+%y-%m-%d'`
cd ~/dotfiles 
git add .
git commit -m "Auto Syncing dotfiles.... $now"
git push
